## CTDN Common Data Model

The CTDN Common Data Model (CDM) is an open community data standard, designed to standardize the structure and content of clinical trial data, **particularly inclusion and exclusion** data to enable efficient matching of patients to clinical trials.

In addition to the inclusion and exclusion criteria, we are working to include fields for additional enrichment of clinical trial records that would improve the accessibility of these trials to a diverse audience and increase their capacity to assess participation.

This site will be used to share the current status of the CTDN Common Data Model and to solicit updates and improvements to the model from the members of the [Clinical Trial Distribution](https://patientfocusedmedicine.org/trial-information-network-project/) Network's working group as well as outside contributors.

The Clinical Trial Distribution Network is managed by [PFMD](https://patientfocusedmedicine.org/). If you would like to join our group please fill out [this form](https://patientfocusedmedicine.org/trial-information-network-project/#join-now) to learn more.

If you want to suggest an update or addition to the CTDN Common Data Model please open an [issue](https://github.com/bgoodmanfsc/bgoodmanfsc.github.io/issues). In addition, a Google Sheet of the tables below can be found at [this link](https://docs.google.com/spreadsheets/d/1I8MiSuAlBokO0dPyOmZ-EJZ2CGQ1OfVCwa_WWP6OX9k/edit?usp=sharing) for either comment or further suggested edits.

------------------------------------------------------------------------

The following model is being proposed for usage in the pilot version of the Clinical Trial Distribution Network. We are open to all contributions or suggested edits to this data model.

### Inclusion / Exclusion Criteria

| Entity                                           | Data Category           | Data Type | Parameters                        | Example                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|--------------------------------------------------|-------------------------|-----------|-----------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| NCT Number                                       | Trial                   | String    | None                              | NCT01980823                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| CT Name - Official Research Title                | Trial                   | String    | None                              | Metformin & Atorvastatin Before Surgery to Study Their Effect on Cancer Cells                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| CT Description - Brief Description of Research   | Trial                   | String    | None                              | The purpose of this study is to determine the effects of combining metformin and atorvastatin treatment in patients with newly diagnosed breast cancer during the interval between breast biopsy and surgery. This study is designed to assess whether tumor proliferation, as measured by the natural log expression of Ki-67 staining of breast tumor cells, is reduced following approximately 2 weeks of treatment with the combination of metformin plus atorvastatin in patients with newly diagnosed breast cancer. |
| Age - Required Age of the Patient                | Inclusion and Exclusion | Integer   | 1 to 120                          | 45                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| Stage - Stage of Disease                         | Inclusion and Exclusion | Array     | Stage 1 to Stage 4                | Stage 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| Biomarker Status - Select Biomarker              | Inclusion and Exclusion | Boolean   | TBD                               | HER2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| Gender - Required Gender of the Patient          | Inclusion and Exclusion | Boolean   | Male, Female                      | Male                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| Phase - Phase of the Clinical Trial              | Trial                   | Array     | Phase 1, Phase 2, Phase 3         | Phase 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| Origin Company - Primary Sponsor of the Research | Trial                   | String    | None                              | Roche                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| Recruitment Status - Still recruiting or not     | Trial                   | Boolean   | Recruiting, Not Recruiting        | Recruiting                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| Location                                         | Trial                   | String    | To be divided into sub types      | Jean Francois Leemans 34, Auderghem Brussels 1160                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| Cancer Type                                      | Inclusion and Exclusion | Array     | Cancer Types - Per Indication     | Breast Cancer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| Cancer SubType                                   | Inclusion and Exclusion | Array     | Cancer Sub Types - Per Indication | Triple-Negative                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Presence of Metastases                           | Inclusion and Exclusion | Boolean   | True, False                       | False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| Treatments                                       | Inclusion               | Boolean   | True, False                       | True                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| Treatments                                       | Exclusion               | Array     | TBD per Indication                | Chemotherapy, Immunotherapy, Hormonal Therapy,                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| Performance Status                               | Inclusion               | Boolean   | ECOG performance status of 0 or 1 | ECOG performance status of 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| Performance Status                               | Exclusion               | Boolean   |                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |

### Plain Language Summary

| Entity                    | Data Category  | Data Type     | Parameters | Example                                                                                                    |
|---------------------------|----------------|---------------|------------|------------------------------------------------------------------------------------------------------------|
| Purpose of the Study      | Plain Language | String        | None       | To study the effects of metformin and atorvastin on breast cancer cells.                                   |
| Who is it for             | Plain Language | String        | None       | Women with stage DCIS, I, stage II, or stage III breast cancer.                                            |
| What is involved          | Plain Language | String        | None       | You will receive the following: Metformin and atorvastatin, by mouth, daily, for 2 weeks prior to surgery" |
| How can I learn more      | Plain Language | String or URL | None       | See below                                                                                                  |
| Resource                  | Plain Language | String        | None       | BreastCancer.org                                                                                           |
| Link                      | Plain Language | url           | None       | [Link to PLS](https://www.breastcancer.org/treatment/hormonal/erds/faslodex%22)                            |
| Visits Required per Month | Plain Language | Integer       | 1 - 10     | 2                                                                                                          |

------------------------------------------------------------------------

### CTDN Parser of Inclusion and Exclusion Criteria

This repository and effort is working in collaboration with an effort to further advance the use of ML to parse inclusion and exclusion criteria in clinical trials, building on the work originally started by Facebook and further extended by our working group partner Roche.
